[font]
size = 15.0

[font.bold]
family = "Iosevka Nerd Font Mono"

[font.italic]
family = "Iosevka Nerd Font Mono"

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[selection]
save_to_clipboard = true

[window]
opacity = 0.87
