[font]
size = 18.0

[font.normal]
family = "IosevkaTerm Nerd Font Propo"

[font.offset]
x = 2
y = 1

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[selection]
save_to_clipboard = true

[shell]
program = "/opt/homebrew/bin/tmux"
args = [ "new-session", "-A", "-D", "-s", "main" ]
