#!/bin/bash
WS=$(i3-msg -t 'get_workspaces' | sed -e 's/{"num/\n{"num/g' | grep \"focused\":true | sed -e 's/,"/\n/g' | grep name | cut -d\" -f 3)
WS_TEXT=$(echo $WS | cut -d \: -f 2)
WS_NR=$(echo $WS | cut -d \: -f 1)
NEW=$(zenity --text="Enter new name:" --entry --title="Rename workspace $WS" --entry-text="$WS_TEXT")
i3-msg "rename workspace \"$WS\" to \"$WS_NR:$NEW\""
